import{S as u,i as l}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();function f(o){const t="42307458-71f98d2a331f0bd294b8fc1ec",i="https://pixabay.com",n="/api/",e=`?key=${t}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=i+n+e;return fetch(r).then(a=>a.json())}let c;const s={form:document.querySelector(".form"),input:document.querySelector(".input-search"),button:document.querySelector(".button"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function p(o){return o.map(t=>`
      <li class="gallery-item"><a href="${t.largeImageURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}"></a>
            <div class="info">
            <p> <span class="info-text">Likes</span> <br/> ${t.likes}</p>
            <p><span class="info-text">Views</span> <br/> ${t.views}</p>
            <p><span class="info-text">Comments</span> <br/> ${t.comments}</p>
            <p><span class="info-text">Downloads</span> <br/> ${t.downloads}</p>
            </div>
            </li>
      `).join("")}function m(o){const t=p(o);s.gallery.innerHTML=t,typeof c<"u"?c.refresh():c=new u(".gallery a",{captionsData:"alt",captionDelay:250})}s.loader.style.display="none";s.form.addEventListener("submit",y);function y(o){if(d(),o.preventDefault(),s.input.value.trim()===""){l.error({message:"Please enter a search query.",position:"topRight",transitionIn:"fadeInLeft"});return}s.gallery.innerHTML="",s.loader.style.display="block";const i=o.target.elements.search.value;f(i).then(n=>{n.hits.length===0?(s.loader.style.display="none",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",transitionIn:"fadeInLeft"})):m(n.hits)}).catch(n=>{l.error({message:n.message||"An error occurred. Please try again later.",position:"topRight",transitionIn:"fadeInLeft"})}).finally(()=>{s.loader.style.display="none"}),o.target.reset()}function d(){s.gallery.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
